---

  - name: Make clair working directory
    file:
      path: "{{ QUAY_ROOT_DIR }}/clair/"
      owner:
      group:
      mode: '0644'
      state: directory

  - name: Deploy quay config
    template:
      src: templates/clair-config.j2
      dest: "{{ QUAY_ROOT_DIR }}/clair/config.yaml"

  - name: Start clair container
    docker_container:
      detach: yes
      restart: yes
      name: "clair"
      published_ports:
        - "6000:6000"
        - "6060:6060"
        - "6061:6061"
      image: "quay.io/redhat/clair-jwt:v3.1.3"
      volumes:
        - "{{ QUAY_ROOT_DIR }}/clair:/clair/config:Z"
    when: QUAY_CLAIR_HTTP_PROXY is not defined and QUAY_CLAIR_HTTPS_PROXY is not defined
    tags:
      - postgres

  - name: Start clair container
    docker_container:
      detach: yes
      restart: yes
      name: "clair"
      env:
        HTTP_PROXY: "{{ QUAY_CLAIR_HTTP_PROXY }}"
        HTTPS_PROXY: "{{ QUAY_CLAIR_HTTPS_PROXY }}"
        NO_PROXY: "{{ QUAY_CLAIR_HTTP_NO_PROXY }}"
      published_ports:
        - "6000:6000"
        - "6060:6060"
        - "6061:6061"
      image: "quay.io/redhat/clair-jwt:v3.1.3"
      volumes:
        - "{{ QUAY_ROOT_DIR }}/clair:/clair/config:Z"
    when: QUAY_CLAIR_HTTP_PROXY is defined or QUAY_CLAIR_HTTPS_PROXY is defined
    tags:
      - postgres
