---
galaxy_info:
  author: Robert de Bock
  role_name: mysql
  description: Install and configure mysql on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8
  min_ansible_container_version: 0.2.0

  platforms:
    - name: Amazon
      versions:
        - Candidate
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - mysql
    - mariadb
    - database
    - installer
    - package
    - centos

dependencies: []
