---
# vars file for mysql
_mysql_packages:
  default:
    - mariadb-server
    - mariadb-devel
    - python2-mysql
  Alpine:
    - mariadb
    - py-mysqldb
  Amazon-2018:
    - mysql-server
    - mysql-devel
    - MySQL-python27
  Amazon:
    - mariadb-server
    - mariadb-devel
    - MySQL-python
  RedHat-7:
    - mariadb-devel
    - mariadb-server
    - MySQL-python
  CentOS-7:
    - mariadb-devel
    - mariadb-server
    - MySQL-python
  CentOS:
    - mysql-devel
    - mysql-server
    - python3-PyMySQL
  Debian:
    - mariadb-server
    - python3-mysqldb
  Fedora:
    - mariadb-server
    - mariadb-devel
    - python3-PyMySQL
  Ubuntu:
    - mariadb-server
    - libssl-dev
    - python3-mysqldb
  openSUSE Leap:
    - libmysqlclient-devel
    - mariadb
    - python-MySQL-python

mysql_packages: "{{ _mysql_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_mysql_packages[ansible_distribution] | default(_mysql_packages['default'])) }}"

_mysql_initialize_command:
  Alpine: /etc/init.d/mariadb setup
  Archlinux: mysql_install_db --basedir=/usr --datadir=/var/lib/mysql

mysql_initialize_command: "{{ _mysql_initialize_command[ansible_os_family] }}"

_mysql_service:
  default: mysql
  Alpine: mariadb
  Amazon: mariadb
  Amazon-2018: mysqld
  Fedora: mariadb
  RedHat-7: mariadb
  RedHat: mysqld

mysql_service: "{{ _mysql_service[ansible_os_family ~ '-' ~ ansible_distribution_major_version] | default(_mysql_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_mysql_service[ansible_distribution] | default(_mysql_service[ansible_os_family] | default(_mysql_service['default'])))) }}"

_mysql_socket:
  default: /var/run/mysql/mysql.sock
  Debian: /var/run/mysqld/mysqld.sock
  RedHat: /var/lib/mysql/mysql.sock

mysql_socket: "{{ _mysql_socket[ansible_os_family] | default(_mysql_socket['default']) }}"
